### ISSUE TITLE
Add Normandy (France) public transport networks (Atoumod)

### ISSUE THREAD

**Issue by NathanBnm** [osm-ToniE/gtfs-feeds#32]
Could you please add the Atoumod network? It's a group that contains all the public buses data in Normandy (France).

GTFS available here: https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands

**Comment by osm-ToniE** [comment]
Thanks,

are the "Agencies" listed on the GTFS page of PTNA: [FR-NOR-Atoumod](https://ptna.openstreetmap.de/gtfs/FR/routes.php?feed=FR-NOR-Atoumod)
- 'network' in OSM terms or
  - if so, shall they be added (step-by-step) also to OSM analysis in PTNA? 
- 'operator' in OSM terms

**Comment by NathanBnm** [comment]
Thank you!

These are all different networks. Maybe it would be better to handle them separately.

For example Twisto is the urban network for the city of Caen and Nomad Car is the interurban network between Normandy cities.

Atoumod is the entity that group them. They make it possible to use the same transport card between them.

**Comment by osm-ToniE** [comment]
> Atoumod is the entity that group them. They make it possible to use the same transport card between them.

Well, that's usually the definition of a 'network': same tickets, same tariffs, ...
The agencies then would be called 'operator' if they operate dependently: 'network' defines the prices, ticket scheme, fare, fare borders, ... and 'network' collects the money and distributes it to the 'operator'.

On the other side, FR-NOR-Atoumod as an OSM analysis would then be quite huge, but [DE-BE-VBB](https://ptna.openstreetmap.de/results/DE/BE/DE-BE-VBB-Analysis.html) = [Berlin / Brandenburg](https://overpass-turbo.eu/map.html?Q=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%28relation%5Bboundary%3Dadministrative%5D%5Badmin_level%3D4%5D%5Bname%7E%27%28Berlin%7CBrandenburg%29%27%5D%3B%29%3Bout+body%3B%3E%3Bout+skel+qt%3B) is the same kind, covers 2 out of 16 states of DE

Just for curiosity: Is there a single tariff system in Normandy?

I had a brief look into Caen and Bayeux and found "Twisto", "ByBus" and "Nomad Car" as 'network' values: so let's go for that
- FR-NOR-Twisto
- FR-NOR-ByBus
- FR-NOR-Nomad_Car
- ...

That will take a while, IL-*, NL-* and ES-CT-* are awaiting completion as well

But I could start with a single FR-NOR-* analysis, so you can familiarize yourself with the OSM analysis.
Any preferences?

**Comment by NathanBnm** [comment]
Each network is independent but is part of the Atoumod conglomerate. Each network has its own fare policy, but all tickets can be loaded onto the same travel card, regardless of the network.

For example, if you buy a one-month subscription on the Twisto network in Caen, you get a travel card on which you can also load a single ticket or a subscription on any other network. And you can have up to 10 tickets or subscriptions on the same card.

I'm currently working on the Nomad Car and Twisto networks. So if they can be added as a priority, that would be great.
