### ISSUE TITLE
gtfs:shape_id not found

### ISSUE THREAD

**Issue by mgageo** [osm-ToniE/gtfs-feeds#33]
For the analysis
https://ptna.openstreetmap.de/results/FR/BRE/FR-BRE-CTRL-Analysis.html
relation
https://www.openstreetmap.org/relation/9215225
gtfs:shape_id 	CTRL:5405$22

I found the data in the file shapes.txt

/mnt/d/web.var/TRANSPORT/KORRIGO$ grep 'CTRL:5405$22,' shapes.txt | head
CTRL:5405$22,47.9041252,-3.1352899,1,0
CTRL:5405$22,47.9041214,-3.1352849,2,0
CTRL:5405$22,47.9041481,-3.135148,3,11
CTRL:5405$22,47.9042091,-3.1351781,4,18
CTRL:5405$22,47.9042435,-3.135191,5,22
CTRL:5405$22,47.9042702,-3.135216,6,25
CTRL:5405$22,47.9042816,-3.1353309,7,34
CTRL:5405$22,47.9043007,-3.135421,8,41
CTRL:5405$22,47.9046021,-3.135437,9,75
CTRL:5405$22,47.9046745,-3.1354511,10,83

**Comment by osm-ToniE** [comment]
Actually it is not a bug in any PTNA repo.

shape_ids and also trip_ids seem not to be stable between two GTFS feed versions
route_ids seem to be stable though

- route_id CTRL:105 can be seen in PTNA's GTFS feed versions 2024-09-27, 2024-10-01 and 2024-10-11 (just updated to the latter one)

- trip_id for bus 105 (CTRL:105) changes with every new feed version
  - 2024-09-27 : [CTRL:4329140:390869](https://ptna.openstreetmap.de/gtfs/FR/single-trip.php?feed=FR-BRE-KorriGo&release_date=2024-09-27&trip_id=CTRL%3A4329140%3A390869) and [CTRL:4329143:390869](https://ptna.openstreetmap.de/gtfs/FR/single-trip.php?feed=FR-BRE-KorriGo&release_date=2024-09-27&trip_id=CTRL%3A4329143%3A390869)
  - 2024-10-01 : [CTRL:4329140:393313](https://ptna.openstreetmap.de/gtfs/FR/single-trip.php?feed=FR-BRE-KorriGo&release_date=2024-10-01&trip_id=CTRL%3A4329140%3A393313) and [CTRL:4329143:393313](https://ptna.openstreetmap.de/gtfs/FR/single-trip.php?feed=FR-BRE-KorriGo&release_date=2024-10-01&trip_id=CTRL%3A4329143%3A393313)
  - 2024-10-11 : [CTRL:4329140:395936](https://ptna.openstreetmap.de/gtfs/FR/single-trip.php?feed=FR-BRE-KorriGo&release_date=2024-10-11&trip_id=CTRL%3A4329140%3A395936) and [CTRL:4329143:395936](https://ptna.openstreetmap.de/gtfs/FR/single-trip.php?feed=FR-BRE-KorriGo&release_date=2024-10-11&trip_id=CTRL%3A4329143%3A395936)

- shape_id for those trips also change with every new feed version
  - 2024-09-27 : CTRL:5209$22 and CTRL:5209$449
  - 2024-10-01 : CTRL:5306$22 and CTRL:5306$443
  - 2024-10-11 : CTRL:5405$22 and CTRL:5405$441

So, my advice would be to **not map trip_id and shape_id** in any route_master/route relation.
You may map route_id in route_master/route relations though and of course in PTNA's CSV data.
